### ISSUE TITLE
DEV: GJ

### ISSUE THREAD

**Issue by kimPM** [HBSIph/PHASE-X.A#7]
- Development, Testing and User Acceptance for General Journal

**Comment by freDeveloperPH** [comment]
Cloning of all existing Financial Actions ; Creating new tables for new schemas

**Comment by IncognitoNoodle** [comment]
Task list for Sprint 1: General Journal 
PS: Per task includes creating/altering existing or non-existing Stored Procedures, altering tables 
- [x] Create Journal Entry Table
- [x] Journalizing of Student's Assessment & Reversed-Asssessment
- [x] Journalizing Scholarships & Discounts
- [x] Journalizing Cashiering Payments & Reversed-Payments
- [x] Journalizing Credit & Debit Memo
- [x]  Journalizing Invoice/s
- [ ] Journalizing Cheques - Not used in DBTC
- [x] Create UI for General Journal
- [x] Crystal Report for General Journal

Journalizing Additional Entries:
- [x]  Expense A/P
- [x]  Expense Dibursement 
- [ ]  Expense P/O - Not used in DBTC
- [ ]  Expense C/A - Not used in DBTC

**Comment by IncognitoNoodle** [comment]
all existing financial action posting already created and finalized - for Q/A

**Comment by IncognitoNoodle** [comment]
Added posting of Reversed - Deferred Revenue
